services:
  - type: web
    name: agrotalk-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: OPENROUTER_API_KEY
        sync: false
      - key: NVIDIA_VISION_KEY
        sync: false
      - key: NVIDIA_TTS_KEY
        sync: false
      - key: NVIDIA_TTS_FUNCTION_ID
        sync: false
      - key: NVIDIA_STT_KEY
        sync: false
      - key: MANDI_API_KEY
        value: 579b464db66ec23bdd000001fe9d36968d1d4e8e62fee0cc92cefecd
      - key: MANDI_API_BASE_URL
        value: https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: FRONTEND_URL
        sync: false
